version: "3.9"

services:

  user:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "3000:3000"  # default
    volumes:
      - .:/usr/src/app
    environment:
      - CPP_PORT=4000
      - PORT=3000
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    command: ["./server", "4000", "1024", "3", "5"]
    restart: unless-stopped

  react:
    build:
      context: ./client-react
    ports:
      - "5173:3000"
    working_dir: /app
    volumes:
      - ./client-react:/app
    stdin_open: true
    tty: true