services:

  user:
    build:
      context: .
      dockerfile: Dockerfile.user
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    command: ["./server", "4000", "1024", "3", "5"]
    restart: unless-stopped
