FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    libgtest-dev \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cd /usr/src/gtest && cmake . && make && cp lib/libgtest*.a /usr/lib || true

RUN git clone https://github.com/google/googletest.git third_party/googletest

WORKDIR /app
COPY . .

RUN make clean && make

CMD ["./server"]  # Let Docker Compose override this
